import type { Workout, WorkoutHistory, SetType } from '../types/workout.ts';
import { showToast } from '../components/Toast.ts';

/**
 * Converts a set type to a clean readable string
 */
function formatSetType(type: SetType): string {
  switch (type) {
    case 'warmup':
      return 'Warmup';
    case 'dropset':
      return 'Dropset';
    case 'failure':
      return 'Failure';
    default:
      return 'Normal';
  }
}

/**
 * Cleans a string for use in filenames
 */
function sanitizeFilename(title: string): string {
  return title
    .trim()
    .toLowerCase()
    .replace(/[\\/:*?"<>|\s]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'workout';
}

/**
 * Downloads a markdown string as a file or shares it via Web Share API
 */
export async function downloadMarkdownFile(filename: string, content: string): Promise<void> {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });

  // If on mobile device with Web Share API file support, allow direct sharing to apps (e.g. Obsidian, Notes)
  if (
    typeof navigator !== 'undefined' &&
    navigator.canShare &&
    typeof File !== 'undefined'
  ) {
    try {
      const file = new File([blob], filename, { type: 'text/markdown' });
      if (navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: filename,
        });
        showToast('Exported to Markdown', 'success');
        return;
      }
    } catch (err) {
      if ((err as Error).name === 'AbortError') return;
      console.warn('Web Share failed, falling back to download:', err);
    }
  }

  // Standard browser file download
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  showToast(`Exported ${filename}`, 'success');
}

/**
 * Generates Markdown for a completed workout from history
 */
export function generateHistoryMarkdown(session: WorkoutHistory): string {
  const startDate = new Date(session.started_at);
  const dateIso = startDate.toISOString().slice(0, 10);
  const dateFormatted = startDate.toLocaleDateString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const durationMin = Math.max(1, Math.round((session.finished_at - session.started_at) / 60000));
  const completedSets = session.snapshot.reduce(
    (sum, ex) => sum + ex.sets.filter((s) => s.is_completed).length,
    0
  );

  let md = `---
title: "${session.title}"
date: ${dateIso}
duration_min: ${durationMin}
volume_kg: ${session.total_volume_kg}
total_reps: ${session.total_reps}
completed_sets: ${completedSets}
tags:
  - workout
  - gym
---

# 🏋️‍♂️ ${session.title}

- **Date:** ${dateFormatted}
- **Duration:** ${durationMin} min
- **Total Volume:** ${session.total_volume_kg.toLocaleString('en-US')} kg
- **Total Reps:** ${session.total_reps}
- **Completed Sets:** ${completedSets}
- **Total Exercises:** ${session.snapshot.length}

---

`;

  session.snapshot.forEach((exercise, idx) => {
    md += `## ${idx + 1}. ${exercise.name}\n\n`;

    if (exercise.notes) {
      md += `> 📝 *Notes: ${exercise.notes}*\n\n`;
    }
    if (exercise.default_rest_sec) {
      md += `> ⏱ *Rest: ${exercise.default_rest_sec}s*\n\n`;
    }

    md += `| Set | Type | Weight (kg) | Reps | Status |\n`;
    md += `|:---:|:----:|:-----------:|:----:|:------:|\n`;

    exercise.sets.forEach((set) => {
      const typeLabel = formatSetType(set.type);
      const weight = set.actual_weight ?? set.target_weight ?? 0;
      const reps = set.actual_reps ?? set.target_reps ?? 0;
      const status = set.is_completed ? '✅ Done' : '⏳ Skipped';
      md += `| ${set.set_number} | ${typeLabel} | ${weight} | ${reps} | ${status} |\n`;
    });

    md += `\n`;
  });

  md += `---\n*Generated by Gym Tracker PWA*\n`;
  return md;
}

/**
 * Generates Markdown for a workout program template
 */
export function generateTemplateMarkdown(workout: Workout): string {
  const updatedDate = new Date(workout.updated_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
  const totalSets = workout.exercises.reduce((acc, ex) => acc + ex.sets.length, 0);

  let md = `---
title: "${workout.title}"
updated: ${new Date(workout.updated_at).toISOString().slice(0, 10)}
exercises_count: ${workout.exercises.length}
total_sets: ${totalSets}
tags:
  - workout-template
  - gym
---

# 📋 ${workout.title}

- **Last Updated:** ${updatedDate}
- **Total Exercises:** ${workout.exercises.length}
- **Total Sets:** ${totalSets}
`;

  if (workout.notes) {
    md += `- **Notes:** ${workout.notes}\n`;
  }

  md += `\n---\n\n`;

  workout.exercises.forEach((exercise, idx) => {
    md += `## ${idx + 1}. ${exercise.name}\n\n`;

    if (exercise.notes) {
      md += `> 📝 *Notes: ${exercise.notes}*\n\n`;
    }
    if (exercise.default_rest_sec) {
      md += `> ⏱ *Default Rest: ${exercise.default_rest_sec}s*\n\n`;
    }

    md += `| Set | Type | Target Weight (kg) | Target Reps |\n`;
    md += `|:---:|:----:|:------------------:|:-----------:|\n`;

    exercise.sets.forEach((set) => {
      const typeLabel = formatSetType(set.type);
      md += `| ${set.set_number} | ${typeLabel} | ${set.target_weight} | ${set.target_reps} |\n`;
    });

    md += `\n`;
  });

  md += `---\n*Generated by Gym Tracker PWA*\n`;
  return md;
}

/**
 * Triggers export of a completed workout from history
 */
export async function exportWorkoutHistoryToMarkdown(session: WorkoutHistory): Promise<void> {
  const content = generateHistoryMarkdown(session);
  const dateStr = new Date(session.started_at).toISOString().slice(0, 10);
  const safeTitle = sanitizeFilename(session.title);
  const filename = `workout_${dateStr}_${safeTitle}.md`;
  await downloadMarkdownFile(filename, content);
}

/**
 * Triggers export of a workout template
 */
export async function exportWorkoutTemplateToMarkdown(workout: Workout): Promise<void> {
  const content = generateTemplateMarkdown(workout);
  const safeTitle = sanitizeFilename(workout.title);
  const filename = `template_${safeTitle}.md`;
  await downloadMarkdownFile(filename, content);
}
